filters:

  - filter_type: file
    source_language: en
    source_file: chrome/android/java/res_ecosia/values/ecosia_strings.xml
    file_format: ANDROID
    translation_files_expression: 'chrome/android/java/res_ecosia/values-<lang>/ecosia_strings.xml'